services:
  mysql-container:
    image: mysql:8
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_db
    ports:
      - "3307:3306"  # expose MySQL externally only if needed
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -proot > /dev/null || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 120s

  product-pricing-app:
    image: animeshtyagi/myapp:latest
    container_name: product-pricing-app
    restart: unless-stopped
    depends_on:
      mysql-container:
        condition: service_healthy

    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/product_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_ADDRESS: 0.0.0.0
      # Optional but recommended for e2-micro resource limits
      JAVA_OPTS: "-Xms128m -Xmx512m"

volumes:
  mysql_data:
