name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          
          sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest .
          sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
        working-directory: ./product
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH to VM and Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/bt-lab-product-test
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
            sudo docker stop myapp || true
            sudo docker rm myapp || true
            sudo docker run -d -p 8080:8080 --name myapp ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest


