name: CI/CD Pipeline - Deploy to VM

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connect to VM and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/project || git clone https://github.com/animesh-tyagi/bt-lab-deploy-test.git project
            cd project
            git pull origin main
            docker compose down
            docker compose build --no-cache
            docker compose up -d
