name: CI/CD Pipeline - Deploy to VM

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connect to VM and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          timeout: 30m
          script: |
            cd ~/bt-lab-deploy-test/product
            git pull origin main
            sudo docker compose down
            sudo docker compose build --no-cache
            sudo docker compose up -d
